name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Export game
      id: export
      uses: firebelley/godot-export@v6.0.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
        relative_project_path: ./detection-simulator
        archive_output: true
        cache: true
        presets_to_export: Linux/X11, macOS, Windows Desktop

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: detection-simulator-exports
        path: ${{ steps.export.outputs.archive_directory }}
        retention-days: 7
