name: Zenodo Release

on:
  release:
    types: [published]
    # This workflow only runs for published releases, not pre-releases
    # The zenodo-release action will check if it's a pre-release and skip if so

jobs:
  zenodo-release:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"  # Only run for stable releases, not pre-releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create source code archive
      id: create-archive
      run: |
        # Create source code archive excluding build artifacts and development files
        git archive --format=zip --prefix=detection-simulator-${{ github.event.release.tag_name }}/ \
          ${{ github.event.release.tag_name }} \
          -o detection-simulator-${{ github.event.release.tag_name }}-source.zip

        echo "archive_path=$(pwd)/detection-simulator-${{ github.event.release.tag_name }}-source.zip" >> $GITHUB_OUTPUT

    - name: Release to Zenodo
      uses: rseng/zenodo-release@main
      with:
        # Zenodo API token (set this as a GitHub secret)
        token: ${{ secrets.ZENODO_TOKEN }}

        # Version from the release tag
        version: ${{ github.event.release.tag_name }}

        # Archive to upload
        archive: ${{ steps.create-archive.outputs.archive_path }}

        # Title and description will be taken from .zenodo.json

        # Use existing DOI for versioning (YOU NEED TO SET THIS)
        # Get this from your existing Zenodo record - it should be the "all versions" DOI
        # Example: "10.5281/zenodo.1234567" (without the version-specific part)
        doi: "10.5281/zenodo.15866228"

        # Optional: Path to .zenodo.json metadata file
        zenodo_json: ".zenodo.json"
